<?php
/*
게시판 스킨 설정 SQL Query 처리 페이지
filename : skin.sql.php
========== 설정 방법 =============
각 변수에 사용자변수 추가 가능
개행(줄바꿈) 을 한뒤 변수를 추가
'test'=>'변수값',
'test1'=>'변수값'
주의점 : 맨 마지막 변수 설정이 끝난뒤에는 , 를 붙이지 말아야함
*/

/////////////////////////////////////////////////////////////////
/*기본 설정*/
$d_skin = "MnM"; // 스킨명 (영문,폴더명과 일치하여야함)
$d_op = array(
	'author'=>'<a href="http://rammenta.ncity.net/" target="_blank">MnM</a>',
	'background_color'=>'#a7e8cc',
	'background_img'=>'',
	'repeat'=>'',
	'notice_border_color'=>'',
	'notice_border_type'=>'',
	'notice_background_color'=>'transparent',
	'table_border_color'=>'#ffe6d9',
	'table_border_size'=>'2px',
	'table_border_type'=>'solid',
	'table_inner_border_color'=>'#ffe6d9',
	'table_inner_border_size'=>'2px',
	'table_inner_border_type'=>'solid',		
	'pic_border_hover'=>'',
	'pic_background_color'=>'#ffffff',
	'table_background_color'=>'#ffcbbf',
	'reply_background_color'=>'#ffffff',
	'reply_text_color'=>'#666666',
	'rereply_bar_color'=>'#ffe6d9',
	'resize'=>'500',
	'table_down'=>'999',
	'size'=>'show',
	'tool'=>'show',
	'time'=>'show',
	'time_type'=>'y.m.d H:i',
	'more_icon'=>'MORE ▼',
	'secret_icon'=>'SECRET',
	'chibi_icon'=>'CHIBI',
	'load_icon'=>'LOAD',
	'reply_icon'=>'R',
	'modify_icon'=>'O',
	'del_icon'=>'X',
	'emoticon_icon'=>'EMOTICON',
	'continue_icon'=>'CONTINUE',
	'login_icon'=>'LOGIN',
	'logout_icon'=>'LOGOUT',
	'op_icon'=>'OP',
	'reflash_icon'=>'REFRESH',
	'admin_icon'=>'SETUP',
	'write_icon'=>'WRITE',
	'hp_icon'=>'URL',
	'painter_icon'=>'★',
	'bootstrap'=>'off',
	'onop_chib'=>'on',
	'onop_mem'=>'on',
	'onop_upright'=>'all',
	'onop_reright'=>'all',
	'onop_rreright'=>'all',
	'autoheight'=>'9999',
	'vertical_imagew'=>'800',
	'autowidth'=>'100',
	'link_color'=>'#ffa89e',
	'link_font'=>'tahoma,돋움',
	'link_size'=>'8pt',
	'link_deco'=>'none',
	'hover_color'=>'#ffcbbf',
	'notice_align'=>'center',
	'notice_textalign'=>'center',
	'noticetext_color'=>'#333333',
	'noticetext_size'=>'8pt',
	'noticetext_font'=>'verdana,돋움',
	'topm_bt_font_color'=>'white',
	'topm_bt_weight'=>'bold',
	'topm_bt_background_color'=>'#ffcbbf',
	'topm_top'=>'show',
	'topm_refre'=>'show',
	'topm_pb'=>'show',
	'topm_color'=>'#666666',
	'topm_font'=>'tahoma,돋움',
	'topm_size'=>'8pt',
	'point_color3'=>'#ffcbbf',
	'topm_border_color'=>'#dddddd 1px',
	'topm_border_type'=>'solid',
	'topm_ip_font_color'=>'#666666',
	'topm_ip_background_color_R'=>'255',
	'topm_ip_background_color_G'=>'255',
	'topm_ip_background_color_B'=>'255',
	'topm_ip_background_alpha'=>'0.8',
	'table_border_radius'=>'6px',
	'point_color1'=>'#ff59a1',
	'point_color2'=>'#666666',
	'point_color4'=>'#28c5ff',
	'lognum_color'=>'black',
	'lognum_font'=>'verdana',
	'lognum_size'=>'8pt',
	'lognum_shadow'=>'0 0 1px rgba(0,0,0,0.3)',
	'lognum_weight'=>'bold',
	'loginfo_color'=>'#666666',
	'loginfo_font'=>'tahoma',
	'loginfo_size'=>'7pt',
	'tool'=>'show',
	'size'=>'show',
	'time'=>'show',
	'logurl_new'=>'original',
	'logurl_url'=>'mix',
	'log_align'=>'center',
	'logtext_align'=>'left',
	'logtext_color'=>'#666666',
	'logtext_font'=>'verdana,돋움',
	'logtext_size'=>'8pt',
	'logop_border_color'=>'1px #999999 ',
	'logop_border_type'=>'solid',
	'logop_background_color'=>'white',
	'logopinp_border_color'=>'#dddddd 1px',
	'logopinp_border_type'=>'solid',
	'logopinp_font_color'=>'#666666',
	'logopinp_background_color'=>'transparent',
	'reply_bmargin'=>'10px',
	'reply_oponoff'=>'show',
	'reply_dataoff'=>'show',
	'rename_color'=>'#333333',
	'rename_font'=>'verdana,돋움',
	'rename_size'=>'8pt',
	'rename_weight'=>'bold',
	'renamewr_color'=>'#ff59a1',
	'time_type_reply'=>'y/m/d(D) H:i:s',
	'retime_color'=>'#aaaaaa',
	'retime_font'=>'tahoma',
	'retime_size'=>'7pt',
	'reply_text_font'=>'verdana,돋움',
	'reply_text_size'=>'8pt',
	'dice_position'=>'front',
	'replyip_color'=>'#dddddd',
	'replyip_font'=>'tahoma',
	'replyip_size'=>'7pt',
	'rereply_mleft'=>'0',
	'rereply_bar_width'=>'3px',
	'memo_background_color'=>'#ffcbbf',
	'memo_color'=>'white',
	'memo_font'=>'tahoma,돋움',
	'memo_size'=>'8pt',
	'memo_weight'=>'bold',
	'memo_posit'=>'top',
	'melinmore'=>'morefirst',
	'comf_rreset'=>'show',
	'comf_emo'=>'show',
	'comf_color'=>'#ffa89e',
	'comf_font'=>'tahoma',
	'comf_size'=>'8pt',
	'comfinp_border_color'=>'#dddddd 1px',
	'comfinp_border_type'=>'solid',
	'comfinp_font_color'=>'#666666',
	'comfinp_background_color_R'=>'200',
	'comfinp_background_color_G'=>'200',
	'comfinp_background_color_B'=>'200',
	'comfinp_background_alpha'=>'0.1',
	'topmtop_icon'=>'TOP',
	'icon'=>'MEMBER',
	'topmjoin_icon'=>'JOIN',
	'topmpm_icon'=>'PROFILE',
	'msecret_icon'=>'MEMBER SECRET',
	'secret_icon_self'=>'YOUR SECRET',
	'lognum_icon'=>'NO #',
	'expand_icon'=>'<img src="skin/MnM/images/expand.png">',
	'logwin_icon'=>'<font color=black size=2>◆</font>',
	'logmore_icon'=>'REPLY MORE ▼',
	'comf_more_icon'=>'COMMENT ▼',
	'comf_emo_icon'=>'EMOTICON',
	'memo_icon'=>'MEMO ::',
	'replyip_icon'=>'IP :',
	'loginfo_weight'=>'normal',
	'topm_member'=>'show',
	'onop_lintrans'=>'on',
	'onop_inputrans'=>'on',
	'point_color5'=>'transparent',
	'scrollbar_on'=>'on',
	'scrollbar_width'=>'8px',
	'scrollbar_height'=>'10px',
	'scrollbar_btbc'=>'0',
	'scrollbar_btbty'=>'none',
	'scrollbar_btbg'=>'#ffa89e',
	'scrollbar_trackbc'=>'0',
	'scrollbar_trackbty'=>'none',
	'scrollbar_trackbg'=>'white',
	'scrollbar_thumbbc'=>'0',
	'scrollbar_thumbbty'=>'none',
	'scrollbar_thumbbg'=>'#8fccb4',
	'secretboard_word'=>'SECRET BOARD',
	'secretboard_wcolor'=>'#fafafa',
	'secretboard_wfam'=>'Franklin Gothic',
	'secretboard_wsize'=>'20px',
	'secretboard_wbg'=>'transparent',
	'secretboard_passcolor'=>'#666',
	'secretboard_passbg'=>'white',
	'secretboard_passwidth'=>'100px',
	'secretboard_passbcr'=>'0',
	'secretboard_passbty'=>'none',
	'secretboard_goword'=>'JOIN',
	'secretboard_gocolor'=>'white',
	'secretboard_gofam'=>'tahoma',
	'secretboard_gosize'=>'8px',
	'secretboard_gobg'=>'#ffa89e',
	'secretboard_gorad'=>'3px',
	'secretboard_wbold'=>'bold'
); // 스킨에서 사용되는 사용자 옵션

////////////////////////////////////////////////////////////
//if($type=="skin_m"){
//	$op = $_POST['op'];
////////////////////////////////////////////////////////////
//}
//if(get_magic_quotes_gpc()) $op = stripslashes($op);

/* 이 아래로는 수정하지 말것!!! 수정시 일어나는 오류에 대해선 책임 지지 않음 */
//게시판 생성시 초기 설정
$skin_insert_string = "INSERT INTO `chibi_skin` (`cid`, `skin_name`, `op`) VALUES ('".mysqli_real_escape_string($chibi_conn, $cid)."', '".mysqli_real_escape_string($chibi_conn, $d_skin)."','".mysqli_real_escape_string($chibi_conn, serialize($d_op))."')";
//게시판설정에서 스킨변경시 초기 설정
$uskin_db = "UPDATE `chibi_skin` SET `cid`='".mysqli_real_escape_string($chibi_conn, $cid)."',  `skin_name`='".mysqli_real_escape_string($chibi_conn, $d_skin)."', `op`='".mysqli_real_escape_string($chibi_conn, serialize($d_op))."' WHERE `cid`='".mysqli_real_escape_string($chibi_conn, $cid)."'";
//스킨설정 페이지에서 업데이트시 설정
$update_db = "UPDATE `chibi_skin` SET `cid`='".mysqli_real_escape_string($chibi_conn, $cid)."',  `skin_name`='".mysqli_real_escape_string($chibi_conn, $d_skin)."', `op`='".mysqli_real_escape_string($chibi_conn, serialize($op))."' WHERE `cid`='".mysqli_real_escape_string($chibi_conn, $cid)."' and `skin_name`='".mysqli_real_escape_string($chibi_conn, $d_skin)."'";
?>